[toolchain]
package_manager = "bun"
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "EmLpgnrx4SB1kQaEZnTMnHEUVsVTJAcuxyPabds52Jed"
whitelist = "5ydZBsgy14hPhvnfoWFg8fpghR91T6uJvtKknbd7yuBK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 1000000"
