[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
whitelisted_vault = "Da6Lqo1Edg3K7FddRvcr4xY7KZbNy1stRtZPqtt6QSUQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bunx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
